'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,Plus,Radio,LoaderCircle,Plug,RotateCcw} from 'lucide-react';
type Message={role:'user'|'assistant';content:string;tools?:string[]};
function Content({text}:{text:string}){return <>{text.split(/(https?:\/\/[^\s<>]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} href={part.replace(/[).,;]+$/,'')} target="_blank" rel="noreferrer">{part}</a>:part)}</>}
export default function AgentChat({defaultAI,customAI}:{defaultAI:boolean;customAI:boolean}){
 const [messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[connected,setConnected]=useState(false);
 const end=useRef<HTMLDivElement>(null);useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages,busy]);
 async function send(){const text=input.trim();if(!text||busy)return;const next:Message[]=[...messages,{role:'user',content:text}];setMessages(next);setInput('');setBusy(true);setError('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.slice(-20).map(({role,content})=>({role,content}))})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to reach your agent.');setMessages([...next,{role:'assistant',content:j.reply,tools:j.tools}]);setConnected(!!j.tools_connected)}catch(e){setError((e as Error).message);setMessages(messages);setInput(text)}finally{setBusy(false)}}
 return <section className={'agent-chat '+(!messages.length?'fresh-chat':'')} aria-label="LeadSignal AI chat"><div className="chat-top"><span><Radio size={20}/>LeadSignal <b>Agent</b></span><button onClick={()=>{setMessages([]);setError('');setConnected(false)}} disabled={busy} title="New conversation"><Plus size={18}/>New chat</button></div><div className="chat-scroll" role="log" aria-live="polite">{messages.length?messages.map((m,i)=><article key={i} className={'chat-message '+m.role}>{m.role==='assistant'&&<span className="assistant-symbol"><Radio size={20}/></span>}<div><div className="message-body"><Content text={m.content}/></div>{!!m.tools?.length&&<small className="used-tools"><Plug size={12}/>{m.tools.length} live tool calls</small>}</div></article>):<div className="chat-welcome"><div className="chat-logo"><Radio size={35}/></div><h1>Who are we finding today?</h1><p>Research a business, explore an opportunity,<br/>or tell me about your ideal client.</p></div>}{busy&&<div className="chat-thinking"><LoaderCircle size={18}/>Working on your request…</div>}<div ref={end}/></div><div className="chat-compose-wrap">{error&&<div role="alert" className="chat-error">{error}<button onClick={send}><RotateCcw size={14}/>Retry</button></div>}<form className="chat-composer" onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="Message LeadSignal" placeholder="Ask anything about your next client…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} rows={3} maxLength={12000}/><div className="chat-composer-bottom"><span>{customAI?'Custom AI':defaultAI?'Default agent':'Agent setup required'}</span><button className="chat-send" type="submit" aria-label="Send message" disabled={busy||!input.trim()}>{busy?<LoaderCircle size={18}/>:<ArrowUp size={20}/>}</button></div></form><div className="chat-disclaimer">{connected?'Composio connected · Live tools available':'Describe your criteria naturally. No filters needed.'}</div></div></section>
}
